"""Pure evidence-only, fail-closed live-provider activation readiness gate."""
from __future__ import annotations
from dataclasses import dataclass
from datetime import datetime
@dataclass(frozen=True,slots=True)
class LiveProviderActivationPolicyV1:
 policy_id:str="";policy_version:str="";provider_id:str="";deployment_environment:str="";allowed_deployment_environments:tuple=();required_checkpoint_id:str="";required_phase_id:str="";require_owner_authorization:bool=True;require_clean_repository:bool=True;require_remote_alignment:bool=True;require_full_regression:bool=True;require_credential_source_configured:bool=True;require_credential_source_redacted:bool=True;require_credential_rotation_plan:bool=True;require_provider_account_verified:bool=True;require_provider_endpoint_allowlisted:bool=True;require_tls_policy_ready:bool=True;require_network_egress_allowlisted:bool=True;require_timeout_policy_ready:bool=True;require_zero_retry_initially:bool=True;require_budget_limit_configured:bool=True;require_reservation_persistence_ready:bool=True;require_reconciliation_ready:bool=True;require_kill_switch_ready:bool=True;require_rollback_plan_ready:bool=True;require_observability_ready:bool=True;require_alerting_ready:bool=True;require_audit_sink_ready:bool=True;require_dry_run_completed:bool=True;require_shadow_comparison_passed:bool=True;require_explicit_live_enablement_commit:bool=True;credential_loading_authorized:bool=False;network_connection_authorized:bool=False;provider_transmission_authorized:bool=False;production_runtime_authorized:bool=False;publication_authorized:bool=False;trading_authorized:bool=False;fail_closed:bool=True
@dataclass(frozen=True,slots=True)
class LiveProviderActivationEvidenceV1:
 activation_evidence_id:str;policy_id:str;provider_id:str;deployment_environment:str;checkpoint_id:str;phase_id:str;repository_head:str;repository_clean:bool;remote_aligned:bool;full_regression_passed:bool;full_regression_test_count:int;owner_authorization_id:str;owner_authorized:bool;credential_source_id:str;credential_source_configured:bool;credential_source_redacted:bool;credential_rotation_plan_id:str;credential_rotation_plan_ready:bool;provider_account_evidence_id:str;provider_account_verified:bool;endpoint_allowlist_id:str;provider_endpoint_allowlisted:bool;tls_policy_id:str;tls_policy_ready:bool;network_egress_policy_id:str;network_egress_allowlisted:bool;timeout_policy_id:str;timeout_policy_ready:bool;retry_disabled:bool;budget_policy_id:str;budget_limit_configured:bool;persistence_readiness_id:str;reservation_persistence_ready:bool;reconciliation_readiness_id:str;reconciliation_ready:bool;kill_switch_id:str;kill_switch_ready:bool;rollback_plan_id:str;rollback_plan_ready:bool;observability_plan_id:str;observability_ready:bool;alerting_plan_id:str;alerting_ready:bool;audit_sink_id:str;audit_sink_ready:bool;dry_run_evidence_id:str;dry_run_completed:bool;shadow_comparison_evidence_id:str;shadow_comparison_passed:bool;live_enablement_commit:str;explicit_live_enablement_commit_present:bool;evaluated_at:datetime
@dataclass(frozen=True,slots=True)
class LiveProviderActivationFailureV1: failure_code:str;safe_message:str;retryable:bool
@dataclass(frozen=True,slots=True)
class LiveProviderActivationDecisionV1:
 activation_evidence_id:str;policy_id:str;provider_id:str;ready:bool;failure_codes:tuple[str,...];repository_ready:bool;credential_governance_ready:bool;provider_account_ready:bool;network_policy_ready:bool;budget_ready:bool;persistence_ready:bool;reconciliation_ready:bool;operational_controls_ready:bool;validation_ready:bool;explicit_enablement_ready:bool;credential_loading_authorized:bool;network_connection_authorized:bool;provider_transmission_authorized:bool;production_runtime_authorized:bool;publication_authorized:bool;trading_authorized:bool
@dataclass(frozen=True,slots=True)
class LiveProviderActivationAuditEvidenceV1:
 activation_evidence_id:str;policy_id:str;provider_id:str;deployment_environment:str;repository_ready:bool;credential_governance_ready:bool;provider_account_ready:bool;network_policy_ready:bool;budget_ready:bool;persistence_ready:bool;reconciliation_ready:bool;operational_controls_ready:bool;validation_ready:bool;explicit_enablement_ready:bool;failure_codes:tuple[str,...];credential_loading_authorized:bool;network_connection_authorized:bool;provider_transmission_authorized:bool;production_runtime_authorized:bool;publication_authorized:bool;trading_authorized:bool
def evaluate_live_provider_activation_readiness_v1(p,e):
 c=[]
 for v,code in ((e.activation_evidence_id,"ACTIVATION_EVIDENCE_ID_EMPTY"),(p.policy_id,"POLICY_ID_EMPTY"),(p.policy_version,"POLICY_VERSION_EMPTY"),(e.provider_id,"PROVIDER_ID_EMPTY"),(e.checkpoint_id,"CHECKPOINT_ID_EMPTY"),(e.phase_id,"PHASE_ID_EMPTY")):
  if not isinstance(v,str) or not v or v!=v.strip():c.append(code)
 if e.policy_id!=p.policy_id:c.append("POLICY_IDENTITY_MISMATCH")
 if e.provider_id!=p.provider_id:c.append("PROVIDER_IDENTITY_MISMATCH")
 if e.deployment_environment not in p.allowed_deployment_environments:c.append("DEPLOYMENT_ENVIRONMENT_NOT_ALLOWED")
 if e.checkpoint_id!=p.required_checkpoint_id:c.append("CHECKPOINT_IDENTITY_MISMATCH")
 if e.phase_id!=p.required_phase_id:c.append("PHASE_IDENTITY_MISMATCH")
 checks=((e.owner_authorized,"OWNER_AUTHORIZATION_REQUIRED"),(e.repository_clean,"REPOSITORY_NOT_CLEAN"),(e.remote_aligned,"REMOTE_NOT_ALIGNED"),(e.full_regression_passed,"FULL_REGRESSION_REQUIRED"),(e.credential_source_configured,"CREDENTIAL_SOURCE_NOT_CONFIGURED"),(e.credential_source_redacted,"CREDENTIAL_SOURCE_NOT_REDACTED"),(e.credential_rotation_plan_ready,"CREDENTIAL_ROTATION_PLAN_NOT_READY"),(e.provider_account_verified,"PROVIDER_ACCOUNT_NOT_VERIFIED"),(e.provider_endpoint_allowlisted,"PROVIDER_ENDPOINT_NOT_ALLOWLISTED"),(e.tls_policy_ready,"TLS_POLICY_NOT_READY"),(e.network_egress_allowlisted,"NETWORK_EGRESS_NOT_ALLOWLISTED"),(e.timeout_policy_ready,"TIMEOUT_POLICY_NOT_READY"),(e.retry_disabled,"RETRY_MUST_BE_DISABLED"),(e.budget_limit_configured,"BUDGET_LIMIT_NOT_CONFIGURED"),(e.reservation_persistence_ready,"RESERVATION_PERSISTENCE_NOT_READY"),(e.reconciliation_ready,"RECONCILIATION_NOT_READY"),(e.kill_switch_ready,"KILL_SWITCH_NOT_READY"),(e.rollback_plan_ready,"ROLLBACK_PLAN_NOT_READY"),(e.observability_ready,"OBSERVABILITY_NOT_READY"),(e.alerting_ready,"ALERTING_NOT_READY"),(e.audit_sink_ready,"AUDIT_SINK_NOT_READY"),(e.dry_run_completed,"DRY_RUN_NOT_COMPLETED"),(e.shadow_comparison_passed,"SHADOW_COMPARISON_NOT_PASSED"),(e.explicit_live_enablement_commit_present,"LIVE_ENABLEMENT_COMMIT_REQUIRED"))
 c.extend(code for ok,code in checks if not ok)
 if not isinstance(e.full_regression_test_count,int) or isinstance(e.full_regression_test_count,bool) or e.full_regression_test_count<=0:c.append("FULL_REGRESSION_COUNT_INVALID")
 c=tuple(sorted(set(c)));ready=not c
 return LiveProviderActivationDecisionV1(e.activation_evidence_id,p.policy_id,e.provider_id,ready,c,e.repository_clean and e.remote_aligned and e.full_regression_passed,e.credential_source_configured and e.credential_source_redacted and e.credential_rotation_plan_ready,e.provider_account_verified,e.provider_endpoint_allowlisted and e.tls_policy_ready and e.network_egress_allowlisted and e.timeout_policy_ready,e.budget_limit_configured,e.reservation_persistence_ready,e.reconciliation_ready,e.kill_switch_ready and e.rollback_plan_ready and e.observability_ready and e.alerting_ready and e.audit_sink_ready,e.dry_run_completed and e.shadow_comparison_passed,e.explicit_live_enablement_commit_present,False,False,False,False,False,False)
def build_live_provider_activation_audit_evidence_v1(p,e,d):
 if d.activation_evidence_id!=e.activation_evidence_id or d.policy_id!=p.policy_id or d.provider_id!=e.provider_id:raise ValueError("activation evidence identity mismatch")
 return LiveProviderActivationAuditEvidenceV1(e.activation_evidence_id,p.policy_id,e.provider_id,e.deployment_environment,d.repository_ready,d.credential_governance_ready,d.provider_account_ready,d.network_policy_ready,d.budget_ready,d.persistence_ready,d.reconciliation_ready,d.operational_controls_ready,d.validation_ready,d.explicit_enablement_ready,d.failure_codes,False,False,False,False,False,False)
