"""Pure, fail-closed readiness-evidence package for a separate owner decision."""
from __future__ import annotations
from dataclasses import dataclass
from datetime import datetime

_F=frozenset(("POLICY_ID_EMPTY","POLICY_VERSION_EMPTY","DEPLOYMENT_ENVIRONMENT_EMPTY","DEPLOYMENT_ENVIRONMENT_NOT_ALLOWED","ACTIVATION_READINESS_POLICY_ID_MISMATCH","RUNTIME_GUARD_POLICY_ID_MISMATCH","BUDGET_POLICY_ID_MISMATCH","PRICING_POLICY_ID_MISMATCH","RESERVATION_POLICY_ID_MISMATCH","USAGE_LEDGER_POLICY_ID_MISMATCH","ALERT_POLICY_ID_MISMATCH","BOUNDARY_EVIDENCE_REQUIRED","BOUNDARY_EVIDENCE_ID_MISMATCH","PROVIDER_ID_MISMATCH","ROUTING_LEVEL_MISMATCH","EXACT_MODEL_ID_MISMATCH","LOCKED_BUDGET_TARGET_MISMATCH","PROVIDER_HARD_CAP_NOT_CONFIRMED","INTERNAL_SOFT_ALERT_NOT_READY","PRICING_NOT_REVALIDATED","RESERVATION_NOT_READY","USAGE_LEDGER_NOT_READY","PRE_RESERVATION_GUARD_NOT_READY","PRE_TRANSMISSION_REVALIDATION_NOT_READY","STALE_USAGE_BLOCK_NOT_READY","BUDGET_CHANGE_BLOCK_NOT_READY","DAILY_LIMIT_BLOCK_NOT_READY","MONTHLY_LIMIT_BLOCK_NOT_READY","HARD_LIMIT_BLOCK_NOT_READY","ALERT_INTENT_NOT_READY","KILL_SWITCH_INTENT_NOT_READY","AUTOMATIC_RETRY_NOT_AUTHORIZED","MANUAL_RECOVERY_NOT_READY","OPERATOR_ATTESTATION_REQUIRED","OPERATOR_ATTESTATION_INCOMPLETE","REVIEWER_EVIDENCE_REQUIRED","REVIEWER_EVIDENCE_INCOMPLETE","OPERATOR_REVIEWER_COLLISION","OWNER_DECISION_RECORD_REQUIRED","OWNER_ACTIVATION_NOT_GRANTED","EVIDENCE_FROM_FUTURE","EVIDENCE_STALE","EVIDENCE_EXPIRED","RUNTIME_ACTIVATION_NOT_AUTHORIZED","RUNTIME_CONFIGURATION_NOT_AUTHORIZED","CREDENTIAL_ONBOARDING_NOT_AUTHORIZED","CREDENTIAL_LOADING_NOT_AUTHORIZED","NETWORK_NOT_AUTHORIZED","PROVIDER_TRANSMISSION_NOT_AUTHORIZED","ALERT_PUBLICATION_NOT_AUTHORIZED","KILL_SWITCH_ACTIVATION_NOT_AUTHORIZED","PUBLICATION_NOT_AUTHORIZED","RAW_CREDENTIAL_EXPOSURE_DETECTED","RAW_PROVIDER_RESPONSE_EXPOSURE_DETECTED","RAW_BILLING_DATA_EXPOSURE_DETECTED","RAW_EXCEPTION_EXPOSURE_DETECTED"))

@dataclass(frozen=True,slots=True)
class BudgetGuardReadinessEvidencePolicyV1:
    policy_id:str="";policy_version:str="";deployment_environment:str="";required_activation_readiness_policy_id:str="";required_runtime_guard_policy_id:str="";required_budget_policy_id:str="";required_pricing_policy_id:str="";required_reservation_policy_id:str="";required_usage_ledger_policy_id:str="";required_alert_policy_id:str="";require_exact_provider_and_model_bindings:bool=False;require_exact_budget_profile:bool=False;require_provider_hard_caps_confirmed:bool=False;require_internal_soft_alerts_ready:bool=False;require_pre_reservation_guard:bool=False;require_pre_transmission_revalidation:bool=False;require_daily_monthly_hard_limit_blocks:bool=False;require_alert_intent:bool=False;require_kill_switch_intent:bool=False;require_manual_recovery:bool=False;require_zero_automatic_retry:bool=False;require_operator_attestation:bool=False;require_independent_reviewer:bool=False;require_owner_activation_decision_record:bool=False;require_evidence_freshness:bool=False;require_redacted_evidence:bool=False;require_pure_audit:bool=False;runtime_activation_authorized:bool=False;runtime_configuration_authorized:bool=False;credential_onboarding_authorized:bool=False;credential_loading_authorized:bool=False;network_authorized:bool=False;provider_transmission_authorized:bool=False;alert_publication_authorized:bool=False;kill_switch_activation_authorized:bool=False;publication_authorized:bool=False;fail_closed:bool=True
@dataclass(frozen=True,slots=True)
class BudgetGuardBoundaryEvidenceBundleV1:
    boundary_bundle_id:str="";policy_id:str="";activation_readiness_policy_id:str="";runtime_guard_policy_id:str="";internal_alert_policy_id:str="";budget_policy_id:str="";pricing_policy_id:str="";reservation_policy_id:str="";usage_ledger_policy_id:str="";provider_budget_configuration_id:str="";provider_hard_cap_confirmation_id:str="";provider_id:str="";routing_level:str="";exact_provider_model_id:str="";locked_budget_target_id:str="";internal_soft_alert_substitution_id:str="";pre_reservation_guard_ready:bool=False;pre_transmission_revalidation_ready:bool=False;stale_usage_block_ready:bool=False;budget_change_block_ready:bool=False;daily_monthly_hard_blocks_ready:bool=False;alert_intent_ready:bool=False;kill_switch_intent_ready:bool=False;manual_recovery_ready:bool=False;automatic_retry_disabled:bool=False;authority_invariants_confirmed:bool=False;redaction_invariants_confirmed:bool=False;audit_purity_confirmed:bool=False;verified_at:datetime|None=None;evidence_expires_at:datetime|None=None;bundle_complete:bool=False;bundle_ready:bool=False
@dataclass(frozen=True,slots=True)
class BudgetGuardOperatorEvidenceAttestationV1:
    operator_attestation_id:str="";policy_id:str="";boundary_bundle_id:str="";operator_id:str="";operator_role:str="";provider_id:str="";routing_level:str="";exact_provider_model_id:str="";locked_budget_target_id:str="";routing_budget_confirmed:bool=False;hard_caps_confirmed:bool=False;internal_soft_alerts_confirmed:bool=False;pricing_confirmed:bool=False;reservation_ledger_confirmed:bool=False;runtime_guard_confirmed:bool=False;alert_kill_switch_confirmed:bool=False;manual_recovery_confirmed:bool=False;automatic_retry_disabled:bool=False;authority_invariants_confirmed:bool=False;redaction_confirmed:bool=False;audit_purity_confirmed:bool=False;verified_at:datetime|None=None;evidence_expires_at:datetime|None=None;attestation_complete:bool=False;attestation_ready:bool=False
@dataclass(frozen=True,slots=True)
class BudgetGuardIndependentReviewEvidenceV1:
    review_evidence_id:str="";policy_id:str="";boundary_bundle_id:str="";operator_attestation_id:str="";reviewer_id:str="";reviewer_role:str="";operator_id:str="";provider_id:str="";routing_level:str="";exact_provider_model_id:str="";locked_budget_target_id:str="";routing_budget_confirmed:bool=False;hard_caps_confirmed:bool=False;internal_soft_alerts_confirmed:bool=False;pricing_reservation_ledger_confirmed:bool=False;runtime_guard_confirmed:bool=False;alert_kill_switch_confirmed:bool=False;manual_recovery_confirmed:bool=False;automatic_retry_disabled:bool=False;authority_invariants_confirmed:bool=False;approved:bool=False;reviewed_at:datetime|None=None;evidence_expires_at:datetime|None=None;review_complete:bool=False;review_ready:bool=False
@dataclass(frozen=True,slots=True)
class BudgetGuardOwnerActivationDecisionRecordV1:
    owner_decision_id:str="";policy_id:str="";boundary_bundle_id:str="";readiness_evidence_accepted:bool=False;runtime_activation_decision_state:str="";runtime_activation_approved:bool=False;credential_onboarding_state:str="";activation_scope:str="";owner_id:str="";decided_at:datetime|None=None;evidence_expires_at:datetime|None=None;rationale_classification:str="";runtime_activation_authorized:bool=False;runtime_configuration_authorized:bool=False;credential_onboarding_authorized:bool=False;credential_loading_authorized:bool=False;network_authorized:bool=False;provider_transmission_authorized:bool=False;alert_publication_authorized:bool=False;kill_switch_activation_authorized:bool=False;publication_authorized:bool=False
@dataclass(frozen=True,slots=True)
class BudgetGuardReadinessEvidenceFailureV1: failure_code:str="";safe_message:str="";retryable:bool=False
@dataclass(frozen=True,slots=True)
class BudgetGuardReadinessEvidenceDecisionV1:
    policy_id:str="";boundary_bundle_id:str="";operator_attestation_id:str="";review_evidence_id:str="";owner_decision_id:str="";provider_id:str="";routing_level:str="";exact_provider_model_id:str="";locked_budget_target_id:str="";routing_ready:bool=False;budget_ready:bool=False;hard_cap_ready:bool=False;internal_soft_alert_ready:bool=False;pricing_ready:bool=False;reservation_ready:bool=False;usage_ledger_ready:bool=False;runtime_guard_ready:bool=False;alert_intent_ready:bool=False;kill_switch_intent_ready:bool=False;manual_recovery_ready:bool=False;operator_ready:bool=False;independent_review_ready:bool=False;owner_decision_state:str="";evidence_fresh:bool=False;failure_codes:tuple[str,...]=();runtime_activation_authorized:bool=False;runtime_configuration_authorized:bool=False;credential_onboarding_authorized:bool=False;credential_loading_authorized:bool=False;network_authorized:bool=False;provider_transmission_authorized:bool=False;alert_publication_authorized:bool=False;kill_switch_activation_authorized:bool=False;publication_authorized:bool=False;ready:bool=False
@dataclass(frozen=True,slots=True)
class BudgetGuardReadinessEvidenceAuditV1:
    policy_id:str="";boundary_bundle_id:str="";operator_attestation_id:str="";review_evidence_id:str="";owner_decision_id:str="";provider_id:str="";routing_level:str="";exact_provider_model_id:str="";locked_budget_target_id:str="";operator_id:str="";reviewer_id:str="";owner_decision_state:str="";routing_ready:bool=False;budget_ready:bool=False;hard_cap_ready:bool=False;internal_soft_alert_ready:bool=False;pricing_ready:bool=False;reservation_ready:bool=False;usage_ledger_ready:bool=False;runtime_guard_ready:bool=False;alert_intent_ready:bool=False;kill_switch_intent_ready:bool=False;manual_recovery_ready:bool=False;evidence_fresh:bool=False;failure_codes:tuple[str,...]=();runtime_activation_authorized:bool=False;runtime_configuration_authorized:bool=False;credential_onboarding_authorized:bool=False;credential_loading_authorized:bool=False;network_authorized:bool=False;provider_transmission_authorized:bool=False;alert_publication_authorized:bool=False;kill_switch_activation_authorized:bool=False;publication_authorized:bool=False;evidence_ready:bool=False

def _codes(v:set[str])->tuple[str,...]: return tuple(sorted(v&_F))
def _auth(p:BudgetGuardReadinessEvidencePolicyV1)->set[str]:
    return {c for x,c in ((p.runtime_activation_authorized,"RUNTIME_ACTIVATION_NOT_AUTHORIZED"),(p.runtime_configuration_authorized,"RUNTIME_CONFIGURATION_NOT_AUTHORIZED"),(p.credential_onboarding_authorized,"CREDENTIAL_ONBOARDING_NOT_AUTHORIZED"),(p.credential_loading_authorized,"CREDENTIAL_LOADING_NOT_AUTHORIZED"),(p.network_authorized,"NETWORK_NOT_AUTHORIZED"),(p.provider_transmission_authorized,"PROVIDER_TRANSMISSION_NOT_AUTHORIZED"),(p.alert_publication_authorized,"ALERT_PUBLICATION_NOT_AUTHORIZED"),(p.kill_switch_activation_authorized,"KILL_SWITCH_ACTIVATION_NOT_AUTHORIZED"),(p.publication_authorized,"PUBLICATION_NOT_AUTHORIZED")) if x}
def evaluate_budget_guard_readiness_evidence_v1(p:BudgetGuardReadinessEvidencePolicyV1,b:BudgetGuardBoundaryEvidenceBundleV1,o:BudgetGuardOperatorEvidenceAttestationV1,r:BudgetGuardIndependentReviewEvidenceV1,d:BudgetGuardOwnerActivationDecisionRecordV1,at:datetime)->BudgetGuardReadinessEvidenceDecisionV1:
    f=_auth(p)
    if not p.policy_id:f.add("POLICY_ID_EMPTY")
    if not p.policy_version:f.add("POLICY_VERSION_EMPTY")
    if not p.deployment_environment:f.add("DEPLOYMENT_ENVIRONMENT_EMPTY")
    elif p.deployment_environment!="CONTROLLED_PRODUCTION":f.add("DEPLOYMENT_ENVIRONMENT_NOT_ALLOWED")
    if b.policy_id!=p.policy_id or o.policy_id!=p.policy_id or r.policy_id!=p.policy_id or d.policy_id!=p.policy_id:f.add("ACTIVATION_READINESS_POLICY_ID_MISMATCH")
    for got,want,code in ((b.activation_readiness_policy_id,p.required_activation_readiness_policy_id,"ACTIVATION_READINESS_POLICY_ID_MISMATCH"),(b.runtime_guard_policy_id,p.required_runtime_guard_policy_id,"RUNTIME_GUARD_POLICY_ID_MISMATCH"),(b.budget_policy_id,p.required_budget_policy_id,"BUDGET_POLICY_ID_MISMATCH"),(b.pricing_policy_id,p.required_pricing_policy_id,"PRICING_POLICY_ID_MISMATCH"),(b.reservation_policy_id,p.required_reservation_policy_id,"RESERVATION_POLICY_ID_MISMATCH"),(b.usage_ledger_policy_id,p.required_usage_ledger_policy_id,"USAGE_LEDGER_POLICY_ID_MISMATCH"),(b.internal_alert_policy_id,p.required_alert_policy_id,"ALERT_POLICY_ID_MISMATCH")):
        if got!=want:f.add(code)
    if not b.boundary_bundle_id:f.add("BOUNDARY_EVIDENCE_REQUIRED")
    if o.boundary_bundle_id!=b.boundary_bundle_id or r.boundary_bundle_id!=b.boundary_bundle_id or d.boundary_bundle_id!=b.boundary_bundle_id:f.add("BOUNDARY_EVIDENCE_ID_MISMATCH")
    if not all((b.provider_id==o.provider_id==r.provider_id,b.routing_level==o.routing_level==r.routing_level,b.exact_provider_model_id==o.exact_provider_model_id==r.exact_provider_model_id)):f.add("PROVIDER_ID_MISMATCH")
    if o.locked_budget_target_id!=b.locked_budget_target_id or r.locked_budget_target_id!=b.locked_budget_target_id:f.add("LOCKED_BUDGET_TARGET_MISMATCH")
    if not b.provider_hard_cap_confirmation_id:f.add("PROVIDER_HARD_CAP_NOT_CONFIRMED")
    checks=((b.pre_reservation_guard_ready,"PRE_RESERVATION_GUARD_NOT_READY"),(b.pre_transmission_revalidation_ready,"PRE_TRANSMISSION_REVALIDATION_NOT_READY"),(b.stale_usage_block_ready,"STALE_USAGE_BLOCK_NOT_READY"),(b.budget_change_block_ready,"BUDGET_CHANGE_BLOCK_NOT_READY"),(b.daily_monthly_hard_blocks_ready,"DAILY_LIMIT_BLOCK_NOT_READY"),(b.alert_intent_ready,"ALERT_INTENT_NOT_READY"),(b.kill_switch_intent_ready,"KILL_SWITCH_INTENT_NOT_READY"),(b.manual_recovery_ready,"MANUAL_RECOVERY_NOT_READY"),(b.automatic_retry_disabled,"AUTOMATIC_RETRY_NOT_AUTHORIZED"))
    for ok,code in checks:
        if not ok:f.add(code)
    if not all((b.bundle_complete,b.bundle_ready,b.authority_invariants_confirmed,b.redaction_invariants_confirmed,b.audit_purity_confirmed,b.internal_soft_alert_substitution_id)):f.add("INTERNAL_SOFT_ALERT_NOT_READY")
    if not o.operator_id:f.add("OPERATOR_ATTESTATION_REQUIRED")
    if not all((o.attestation_complete,o.attestation_ready,o.routing_budget_confirmed,o.hard_caps_confirmed,o.internal_soft_alerts_confirmed,o.pricing_confirmed,o.reservation_ledger_confirmed,o.runtime_guard_confirmed,o.alert_kill_switch_confirmed,o.manual_recovery_confirmed,o.automatic_retry_disabled,o.authority_invariants_confirmed,o.redaction_confirmed,o.audit_purity_confirmed)):f.add("OPERATOR_ATTESTATION_INCOMPLETE")
    if not r.reviewer_id:f.add("REVIEWER_EVIDENCE_REQUIRED")
    if not all((r.review_complete,r.review_ready,r.approved,r.routing_budget_confirmed,r.hard_caps_confirmed,r.internal_soft_alerts_confirmed,r.pricing_reservation_ledger_confirmed,r.runtime_guard_confirmed,r.alert_kill_switch_confirmed,r.manual_recovery_confirmed,r.automatic_retry_disabled,r.authority_invariants_confirmed)):f.add("REVIEWER_EVIDENCE_INCOMPLETE")
    if r.operator_attestation_id!=o.operator_attestation_id:f.add("REVIEWER_EVIDENCE_REQUIRED")
    if r.reviewer_id==o.operator_id or r.operator_id!=o.operator_id:f.add("OPERATOR_REVIEWER_COLLISION")
    if not d.owner_decision_id:f.add("OWNER_DECISION_RECORD_REQUIRED")
    fresh=True
    for start,end in ((b.verified_at,b.evidence_expires_at),(o.verified_at,o.evidence_expires_at),(r.reviewed_at,r.evidence_expires_at),(d.decided_at,d.evidence_expires_at)):
        if start is None or end is None:f.add("EVIDENCE_STALE");fresh=False
        elif start>at:f.add("EVIDENCE_FROM_FUTURE");fresh=False
        elif end<=at:f.add("EVIDENCE_EXPIRED");fresh=False
    routing=not any(x in f for x in ("PROVIDER_ID_MISMATCH","ROUTING_LEVEL_MISMATCH","EXACT_MODEL_ID_MISMATCH"));budget="LOCKED_BUDGET_TARGET_MISMATCH" not in f;runtime=all(x not in f for x in ("PRE_RESERVATION_GUARD_NOT_READY","PRE_TRANSMISSION_REVALIDATION_NOT_READY","STALE_USAGE_BLOCK_NOT_READY","BUDGET_CHANGE_BLOCK_NOT_READY"));codes=_codes(f)
    return BudgetGuardReadinessEvidenceDecisionV1(p.policy_id,b.boundary_bundle_id,o.operator_attestation_id,r.review_evidence_id,d.owner_decision_id,b.provider_id,b.routing_level,b.exact_provider_model_id,b.locked_budget_target_id,routing,budget,bool(b.provider_hard_cap_confirmation_id),bool(b.internal_soft_alert_substitution_id),b.pre_transmission_revalidation_ready,True,True,runtime,b.alert_intent_ready,b.kill_switch_intent_ready,b.manual_recovery_ready,o.attestation_ready,r.review_ready,d.runtime_activation_decision_state,fresh,codes,False,False,False,False,False,False,False,False,False,not codes)
def build_budget_guard_readiness_evidence_audit_v1(p,b,o,r,d,x):
    if x.policy_id!=p.policy_id or x.boundary_bundle_id!=b.boundary_bundle_id or x.operator_attestation_id!=o.operator_attestation_id or x.review_evidence_id!=r.review_evidence_id or x.owner_decision_id!=d.owner_decision_id:raise ValueError("readiness identities must align")
    return BudgetGuardReadinessEvidenceAuditV1(p.policy_id,b.boundary_bundle_id,o.operator_attestation_id,r.review_evidence_id,d.owner_decision_id,b.provider_id,b.routing_level,b.exact_provider_model_id,b.locked_budget_target_id,o.operator_id,r.reviewer_id,x.owner_decision_state,x.routing_ready,x.budget_ready,x.hard_cap_ready,x.internal_soft_alert_ready,x.pricing_ready,x.reservation_ready,x.usage_ledger_ready,x.runtime_guard_ready,x.alert_intent_ready,x.kill_switch_intent_ready,x.manual_recovery_ready,x.evidence_fresh,x.failure_codes,False,False,False,False,False,False,False,False,False,True)
