"""RED contract for fake-only, read-only provider transmission reconciliation."""
from __future__ import annotations
from dataclasses import FrozenInstanceError, fields, is_dataclass
from datetime import UTC, datetime
import pytest
from engine.phase_12_provider_transmission_reconciliation_contract_v1 import (
 ProviderTransmissionReconciliationPolicyV1, ProviderTransmissionReconciliationBindingV1, ProviderTransmissionReconciliationRequestV1, ProviderTransmissionReconciliationFailureV1, ProviderTransmissionReconciliationEvidenceV1, ProviderTransmissionReconciliationResultV1, ProviderTransmissionReconciliationAuditEvidenceV1, ProviderTransmissionReconciliationSourceV1, reconcile_provider_transmission_v1, build_provider_transmission_reconciliation_audit_evidence_v1,
)

_NOW=datetime(2030,1,6,12,0,tzinfo=UTC)
_POLICY=("policy_id","policy_version","provider_id","allowed_prior_outcomes","allowed_reconciliation_classifications","require_recorded_attempt","require_attempt_identity_alignment","require_provider_request_identity_alignment","require_reservation_identity_alignment","require_persistence_command_identity_alignment","require_idempotency_identity_alignment","require_provider_reference_alignment","require_read_only_source","require_response_redaction","source_invocation_limit","retransmission_allowed","retry_allowed","provider_polling_authorized","reconciliation_authorized","provider_execution_inference_authorized","reservation_mutation_authorized","persistence_mutation_authorized","fail_closed")
_BINDING=("binding_id","provider_id","request_route_id","endpoint_configuration_id","transmission_attempt_id","transmission_policy_id","transmission_binding_id","authenticated_request_descriptor_id","provider_request_id","payload_identity","reservation_id","persistence_command_id","idempotency_key","response_envelope_id","provider_request_reference_id","prior_outcome_classification","prior_attempt_recorded","prior_response_received","prior_provider_acknowledged","prior_recovery_required","binding_verified","reconciliation_authorized","provider_execution_inference_authorized","reservation_mutation_authorized","persistence_mutation_authorized")
_REQUEST=("reconciliation_request_id","binding_id","provider_id","transmission_attempt_id","provider_request_id","reservation_id","persistence_command_id","idempotency_key","provider_request_reference_id","requested_at","binding_valid","prior_attempt_recorded","prior_recovery_required","reconciliation_authorized","provider_execution_inference_authorized")
_EVIDENCE=("reconciliation_evidence_id","reconciliation_request_id","provider_id","transmission_attempt_id","provider_request_id","provider_request_reference_id","response_envelope_id","reconciliation_classification","provider_status_identity","provider_status_confirmed","provider_acknowledged","provider_execution_confirmed","evidence_observed_at","evidence_source_identity","response_redaction_valid","evidence_complete","evidence_conflicting","evidence_corrupt")
_RESULT=("reconciliation_request_id","binding_id","policy_id","accepted","failure_codes","reconciliation_classification","policy_valid","binding_valid","prior_attempt_valid","source_invoked","evidence_received","evidence_valid","reconciled","provider_status_confirmed","provider_acknowledged","provider_execution_confirmed","recovery_required","reservation_mutated","persistence_mutated","retransmission_attempted","retry_attempted","polling_attempted")
_AUDIT=("reconciliation_request_id","binding_id","policy_id","provider_id","transmission_attempt_id","provider_request_id","reservation_id","persistence_command_id","idempotency_key","provider_request_reference_id","prior_attempt_recorded","prior_outcome_classification","source_invocation_count","reconciliation_classification","provider_acknowledged","provider_execution_confirmed","evidence_complete","evidence_conflicting","evidence_corrupt","response_redaction_valid","recovery_required","failure_codes","reservation_mutated","persistence_mutated","retransmission_attempted","retry_attempted","polling_attempted")
_FAILURE=("failure_code","safe_message","retryable")
_CODES={"RECONCILIATION_REQUEST_ID_EMPTY","BINDING_ID_EMPTY","POLICY_ID_EMPTY","POLICY_VERSION_EMPTY","PROVIDER_ID_EMPTY","TRANSMISSION_ATTEMPT_ID_EMPTY","TRANSMISSION_POLICY_ID_EMPTY","TRANSMISSION_BINDING_ID_EMPTY","AUTHENTICATED_REQUEST_DESCRIPTOR_ID_EMPTY","PROVIDER_REQUEST_ID_EMPTY","PAYLOAD_IDENTITY_EMPTY","RESERVATION_ID_EMPTY","PERSISTENCE_COMMAND_ID_EMPTY","IDEMPOTENCY_KEY_EMPTY","PROVIDER_REQUEST_REFERENCE_ID_EMPTY","IDENTIFIER_NOT_NORMALIZED","POLICY_IDENTITY_MISMATCH","BINDING_IDENTITY_MISMATCH","PROVIDER_IDENTITY_MISMATCH","TRANSMISSION_ATTEMPT_IDENTITY_MISMATCH","TRANSMISSION_POLICY_IDENTITY_MISMATCH","TRANSMISSION_BINDING_IDENTITY_MISMATCH","REQUEST_DESCRIPTOR_IDENTITY_MISMATCH","PROVIDER_REQUEST_IDENTITY_MISMATCH","PAYLOAD_IDENTITY_MISMATCH","RESERVATION_IDENTITY_MISMATCH","PERSISTENCE_COMMAND_IDENTITY_MISMATCH","IDEMPOTENCY_IDENTITY_MISMATCH","PROVIDER_REFERENCE_IDENTITY_MISMATCH","RESPONSE_ENVELOPE_IDENTITY_MISMATCH","BINDING_NOT_VERIFIED","PRIOR_ATTEMPT_NOT_RECORDED","PRIOR_OUTCOME_NOT_ALLOWED","RECOVERY_NOT_REQUIRED","RECONCILIATION_NOT_AUTHORIZED","PROVIDER_EXECUTION_INFERENCE_NOT_AUTHORIZED","SOURCE_INVOCATION_LIMIT_INVALID","RECONCILIATION_SOURCE_REQUIRED","RECONCILIATION_SOURCE_INVOCATION_FAILED","SOURCE_INVOKED_MORE_THAN_ONCE","RECONCILIATION_EVIDENCE_MISSING","RECONCILIATION_EVIDENCE_INVALID","RECONCILIATION_CLASSIFICATION_NOT_ALLOWED","PROVIDER_STATUS_NOT_CONFIRMED","PROVIDER_ACKNOWLEDGEMENT_CONFLICT","PROVIDER_EXECUTION_EVIDENCE_CONFLICT","EVIDENCE_INCOMPLETE","EVIDENCE_CONFLICTING","EVIDENCE_CORRUPT","RESPONSE_REDACTION_INVALID","RECONCILIATION_OUTCOME_UNRESOLVED","RETRANSMISSION_NOT_AUTHORIZED","RETRY_NOT_AUTHORIZED","PROVIDER_POLLING_NOT_AUTHORIZED","RESERVATION_MUTATION_NOT_AUTHORIZED","PERSISTENCE_MUTATION_NOT_AUTHORIZED","RAW_REQUEST_EXPOSURE_DETECTED","RAW_RESPONSE_EXPOSURE_DETECTED","RAW_SECRET_EXPOSURE_DETECTED","RAW_HEADER_EXPOSURE_DETECTED","RAW_ENDPOINT_EXPOSURE_DETECTED","RAW_EXCEPTION_EXPOSURE_DETECTED"}

class _FakeEvidence:
 def __init__(self,classification="FAKE_CONFIRMED_ACCEPTED"):
  self.reconciliation_evidence_id="fake-reconciliation-evidence-v1";self.reconciliation_request_id="reconciliation-request-v1";self.provider_id="provider-v1";self.transmission_attempt_id="transmission-attempt-v1";self.provider_request_id="provider-request-v1";self.provider_request_reference_id="provider-request-v1";self.response_envelope_id="response-envelope-v1";self.reconciliation_classification=classification;self.provider_status_identity="fake-provider-status-v1";self.provider_status_confirmed=True;self.provider_acknowledged=classification=="FAKE_CONFIRMED_ACCEPTED";self.provider_execution_confirmed=False;self.evidence_observed_at=_NOW;self.evidence_source_identity="fake-reconciliation-source-v1";self.response_redaction_valid=True;self.evidence_complete=True;self.evidence_conflicting=False;self.evidence_corrupt=False
 def __repr__(self):return "_FakeEvidence(REDACTED)"
class _FakeSource:
 def __init__(self,evidence):self.evidence=evidence;self.calls=0
 def read_reconciliation_evidence(self,reconciliation_request):self.calls+=1;return self.evidence
def _policy(**x):
 d=dict(policy_id="reconciliation-policy-v1",policy_version="V1",provider_id="provider-v1",allowed_prior_outcomes=("ATTEMPT_OUTCOME_UNCERTAIN",),allowed_reconciliation_classifications=("FAKE_CONFIRMED_ACCEPTED","FAKE_CONFIRMED_REJECTED","FAKE_NOT_FOUND","FAKE_STILL_PENDING","FAKE_EVIDENCE_MALFORMED","FAKE_EVIDENCE_CONFLICT","FAKE_EVIDENCE_CORRUPT","RECONCILIATION_OUTCOME_UNRESOLVED"),require_recorded_attempt=True,require_attempt_identity_alignment=True,require_provider_request_identity_alignment=True,require_reservation_identity_alignment=True,require_persistence_command_identity_alignment=True,require_idempotency_identity_alignment=True,require_provider_reference_alignment=True,require_read_only_source=True,require_response_redaction=True,source_invocation_limit=1,retransmission_allowed=False,retry_allowed=False,provider_polling_authorized=False,reconciliation_authorized=True,provider_execution_inference_authorized=False,reservation_mutation_authorized=False,persistence_mutation_authorized=False,fail_closed=True);d.update(x);return ProviderTransmissionReconciliationPolicyV1(**d)
def _binding(**x):
 d=dict(binding_id="reconciliation-binding-v1",provider_id="provider-v1",request_route_id="provider-route-v1",endpoint_configuration_id="endpoint-config-v1",transmission_attempt_id="transmission-attempt-v1",transmission_policy_id="transmission-policy-v1",transmission_binding_id="transmission-binding-v1",authenticated_request_descriptor_id="authenticated-request-descriptor-v1",provider_request_id="provider-request-v1",payload_identity="payload-identity-v1",reservation_id="reservation-v1",persistence_command_id="persistence-command-v1",idempotency_key="idempotency-key-v1",response_envelope_id="response-envelope-v1",provider_request_reference_id="provider-request-v1",prior_outcome_classification="ATTEMPT_OUTCOME_UNCERTAIN",prior_attempt_recorded=True,prior_response_received=True,prior_provider_acknowledged=False,prior_recovery_required=True,binding_verified=True,reconciliation_authorized=True,provider_execution_inference_authorized=False,reservation_mutation_authorized=False,persistence_mutation_authorized=False);d.update(x);return ProviderTransmissionReconciliationBindingV1(**d)
def _request(**x):
 d=dict(reconciliation_request_id="reconciliation-request-v1",binding_id="reconciliation-binding-v1",provider_id="provider-v1",transmission_attempt_id="transmission-attempt-v1",provider_request_id="provider-request-v1",reservation_id="reservation-v1",persistence_command_id="persistence-command-v1",idempotency_key="idempotency-key-v1",provider_request_reference_id="provider-request-v1",requested_at=_NOW,binding_valid=True,prior_attempt_recorded=True,prior_recovery_required=True,reconciliation_authorized=True,provider_execution_inference_authorized=False);d.update(x);return ProviderTransmissionReconciliationRequestV1(**d)
def _frozen(x):assert is_dataclass(x) and type(x).__dataclass_params__.frozen and "__dict__" not in type(x).__slots__
def test_public_contract_is_immutable_narrow_and_read_only():
 assert tuple(f.name for f in fields(ProviderTransmissionReconciliationPolicyV1))==_POLICY
 assert tuple(f.name for f in fields(ProviderTransmissionReconciliationBindingV1))==_BINDING
 assert tuple(f.name for f in fields(ProviderTransmissionReconciliationRequestV1))==_REQUEST
 assert tuple(f.name for f in fields(ProviderTransmissionReconciliationEvidenceV1))==_EVIDENCE
 assert tuple(f.name for f in fields(ProviderTransmissionReconciliationResultV1))==_RESULT
 assert tuple(f.name for f in fields(ProviderTransmissionReconciliationAuditEvidenceV1))==_AUDIT
 assert tuple(f.name for f in fields(ProviderTransmissionReconciliationFailureV1))==_FAILURE
 assert {"read_reconciliation_evidence"}.issubset(dir(ProviderTransmissionReconciliationSourceV1))
 assert not {"get","post","send","request","retry","transmit","mutate"}.intersection(dir(ProviderTransmissionReconciliationSourceV1))
 result=reconcile_provider_transmission_v1(_policy(),_binding(),_request(),None);evidence=build_provider_transmission_reconciliation_audit_evidence_v1(_policy(),_binding(),_request(),result)
 for x in (_policy(),_binding(),_request(),result,evidence):_frozen(x)
 with pytest.raises(FrozenInstanceError):_policy().reconciliation_authorized=False # type: ignore[misc]
def test_preconditions_fail_before_fake_source():
 source=_FakeSource(_FakeEvidence());result=reconcile_provider_transmission_v1(_policy(reconciliation_authorized=False),_binding(binding_verified=False,prior_attempt_recorded=False),_request(prior_recovery_required=False),source)
 assert {"BINDING_NOT_VERIFIED","PRIOR_ATTEMPT_NOT_RECORDED","RECOVERY_NOT_REQUIRED","RECONCILIATION_NOT_AUTHORIZED"}.issubset(result.failure_codes)
 assert tuple(result.failure_codes)==tuple(sorted(result.failure_codes)) and set(result.failure_codes).issubset(_CODES) and source.calls==0
 assert (result.source_invoked,result.reconciled,result.provider_status_confirmed,result.provider_execution_confirmed,result.reservation_mutated,result.persistence_mutated,result.retransmission_attempted,result.retry_attempted,result.polling_attempted)==(False,)*9
def test_one_fake_confirmed_read_is_redacted_and_non_mutating():
 source=_FakeSource(_FakeEvidence());result=reconcile_provider_transmission_v1(_policy(),_binding(),_request(),source)
 assert result.accepted and result.reconciliation_classification=="FAKE_CONFIRMED_ACCEPTED" and source.calls==1
 assert (result.source_invoked,result.evidence_received,result.reconciled,result.provider_status_confirmed,result.provider_acknowledged)==(True,)*5
 assert (result.provider_execution_confirmed,result.reservation_mutated,result.persistence_mutated,result.retransmission_attempted,result.retry_attempted,result.polling_attempted)==(False,)*6
def test_unresolved_fake_evidence_requires_recovery_without_second_read():
 source=_FakeSource(_FakeEvidence("RECONCILIATION_OUTCOME_UNRESOLVED"));result=reconcile_provider_transmission_v1(_policy(),_binding(),_request(),source)
 assert not result.accepted and result.reconciliation_classification=="RECONCILIATION_OUTCOME_UNRESOLVED" and "RECONCILIATION_OUTCOME_UNRESOLVED" in result.failure_codes and result.recovery_required and source.calls==1
def test_audit_is_identity_bound_deterministic_and_does_not_read_again():
 source=_FakeSource(_FakeEvidence());p,b,r=_policy(),_binding(),_request();result=reconcile_provider_transmission_v1(p,b,r,source);evidence=build_provider_transmission_reconciliation_audit_evidence_v1(p,b,r,result)
 assert evidence==build_provider_transmission_reconciliation_audit_evidence_v1(p,b,r,result) and source.calls==1
 with pytest.raises(ValueError):build_provider_transmission_reconciliation_audit_evidence_v1(p,_binding(provider_id="other-provider-v1"),r,result)
