"""RED contract for an evidence-only, fail-closed live-provider readiness gate."""
from __future__ import annotations
from dataclasses import FrozenInstanceError, fields, is_dataclass
from datetime import UTC, datetime
import pytest
from engine.phase_12_live_provider_activation_readiness_gate_v1 import (LiveProviderActivationPolicyV1,LiveProviderActivationEvidenceV1,LiveProviderActivationFailureV1,LiveProviderActivationDecisionV1,LiveProviderActivationAuditEvidenceV1,evaluate_live_provider_activation_readiness_v1,build_live_provider_activation_audit_evidence_v1)
_NOW=datetime(2030,1,7,12,0,tzinfo=UTC)
_P=("policy_id","policy_version","provider_id","deployment_environment","allowed_deployment_environments","required_checkpoint_id","required_phase_id","require_owner_authorization","require_clean_repository","require_remote_alignment","require_full_regression","require_credential_source_configured","require_credential_source_redacted","require_credential_rotation_plan","require_provider_account_verified","require_provider_endpoint_allowlisted","require_tls_policy_ready","require_network_egress_allowlisted","require_timeout_policy_ready","require_zero_retry_initially","require_budget_limit_configured","require_reservation_persistence_ready","require_reconciliation_ready","require_kill_switch_ready","require_rollback_plan_ready","require_observability_ready","require_alerting_ready","require_audit_sink_ready","require_dry_run_completed","require_shadow_comparison_passed","require_explicit_live_enablement_commit","credential_loading_authorized","network_connection_authorized","provider_transmission_authorized","production_runtime_authorized","publication_authorized","trading_authorized","fail_closed")
_E=("activation_evidence_id","policy_id","provider_id","deployment_environment","checkpoint_id","phase_id","repository_head","repository_clean","remote_aligned","full_regression_passed","full_regression_test_count","owner_authorization_id","owner_authorized","credential_source_id","credential_source_configured","credential_source_redacted","credential_rotation_plan_id","credential_rotation_plan_ready","provider_account_evidence_id","provider_account_verified","endpoint_allowlist_id","provider_endpoint_allowlisted","tls_policy_id","tls_policy_ready","network_egress_policy_id","network_egress_allowlisted","timeout_policy_id","timeout_policy_ready","retry_disabled","budget_policy_id","budget_limit_configured","persistence_readiness_id","reservation_persistence_ready","reconciliation_readiness_id","reconciliation_ready","kill_switch_id","kill_switch_ready","rollback_plan_id","rollback_plan_ready","observability_plan_id","observability_ready","alerting_plan_id","alerting_ready","audit_sink_id","audit_sink_ready","dry_run_evidence_id","dry_run_completed","shadow_comparison_evidence_id","shadow_comparison_passed","live_enablement_commit","explicit_live_enablement_commit_present","evaluated_at")
_D=("activation_evidence_id","policy_id","provider_id","ready","failure_codes","repository_ready","credential_governance_ready","provider_account_ready","network_policy_ready","budget_ready","persistence_ready","reconciliation_ready","operational_controls_ready","validation_ready","explicit_enablement_ready","credential_loading_authorized","network_connection_authorized","provider_transmission_authorized","production_runtime_authorized","publication_authorized","trading_authorized")
_A=("activation_evidence_id","policy_id","provider_id","deployment_environment","repository_ready","credential_governance_ready","provider_account_ready","network_policy_ready","budget_ready","persistence_ready","reconciliation_ready","operational_controls_ready","validation_ready","explicit_enablement_ready","failure_codes","credential_loading_authorized","network_connection_authorized","provider_transmission_authorized","production_runtime_authorized","publication_authorized","trading_authorized")
_F=("failure_code","safe_message","retryable")
_C={"ACTIVATION_EVIDENCE_ID_EMPTY","POLICY_ID_EMPTY","POLICY_VERSION_EMPTY","PROVIDER_ID_EMPTY","DEPLOYMENT_ENVIRONMENT_EMPTY","DEPLOYMENT_ENVIRONMENT_NOT_ALLOWED","CHECKPOINT_ID_EMPTY","PHASE_ID_EMPTY","IDENTIFIER_NOT_NORMALIZED","POLICY_IDENTITY_MISMATCH","PROVIDER_IDENTITY_MISMATCH","CHECKPOINT_IDENTITY_MISMATCH","PHASE_IDENTITY_MISMATCH","OWNER_AUTHORIZATION_REQUIRED","REPOSITORY_NOT_CLEAN","REMOTE_NOT_ALIGNED","FULL_REGRESSION_REQUIRED","FULL_REGRESSION_COUNT_INVALID","CREDENTIAL_SOURCE_NOT_CONFIGURED","CREDENTIAL_SOURCE_NOT_REDACTED","CREDENTIAL_ROTATION_PLAN_NOT_READY","PROVIDER_ACCOUNT_NOT_VERIFIED","PROVIDER_ENDPOINT_NOT_ALLOWLISTED","TLS_POLICY_NOT_READY","NETWORK_EGRESS_NOT_ALLOWLISTED","TIMEOUT_POLICY_NOT_READY","RETRY_MUST_BE_DISABLED","BUDGET_LIMIT_NOT_CONFIGURED","RESERVATION_PERSISTENCE_NOT_READY","RECONCILIATION_NOT_READY","KILL_SWITCH_NOT_READY","ROLLBACK_PLAN_NOT_READY","OBSERVABILITY_NOT_READY","ALERTING_NOT_READY","AUDIT_SINK_NOT_READY","DRY_RUN_NOT_COMPLETED","SHADOW_COMPARISON_NOT_PASSED","LIVE_ENABLEMENT_COMMIT_REQUIRED","CREDENTIAL_LOADING_NOT_AUTHORIZED","NETWORK_CONNECTION_NOT_AUTHORIZED","PROVIDER_TRANSMISSION_NOT_AUTHORIZED","PRODUCTION_RUNTIME_NOT_AUTHORIZED","PUBLICATION_NOT_AUTHORIZED","TRADING_NOT_AUTHORIZED","RAW_SECRET_EXPOSURE_DETECTED","RAW_ENDPOINT_EXPOSURE_DETECTED","RAW_EXCEPTION_EXPOSURE_DETECTED"}
def _p(**x):
 d=dict(policy_id="live-activation-policy-v1",policy_version="V1",provider_id="provider-v1",deployment_environment="CONTROLLED_PRODUCTION",allowed_deployment_environments=("CONTROLLED_PRODUCTION",),required_checkpoint_id="checkpoint-v1",required_phase_id="phase-12",require_owner_authorization=True,require_clean_repository=True,require_remote_alignment=True,require_full_regression=True,require_credential_source_configured=True,require_credential_source_redacted=True,require_credential_rotation_plan=True,require_provider_account_verified=True,require_provider_endpoint_allowlisted=True,require_tls_policy_ready=True,require_network_egress_allowlisted=True,require_timeout_policy_ready=True,require_zero_retry_initially=True,require_budget_limit_configured=True,require_reservation_persistence_ready=True,require_reconciliation_ready=True,require_kill_switch_ready=True,require_rollback_plan_ready=True,require_observability_ready=True,require_alerting_ready=True,require_audit_sink_ready=True,require_dry_run_completed=True,require_shadow_comparison_passed=True,require_explicit_live_enablement_commit=True,credential_loading_authorized=False,network_connection_authorized=False,provider_transmission_authorized=False,production_runtime_authorized=False,publication_authorized=False,trading_authorized=False,fail_closed=True);d.update(x);return LiveProviderActivationPolicyV1(**d)
def _e(**x):
 d={n:(True if n.startswith("repository_") or n.endswith("_ready") or n in {"remote_aligned","full_regression_passed","owner_authorized","credential_source_configured","credential_source_redacted","provider_account_verified","provider_endpoint_allowlisted","network_egress_allowlisted","timeout_policy_ready","retry_disabled","budget_limit_configured","reservation_persistence_ready","reconciliation_ready","dry_run_completed","shadow_comparison_passed","explicit_live_enablement_commit_present"} else "evidence-v1") for n in _E};d.update(dict(activation_evidence_id="activation-evidence-v1",policy_id="live-activation-policy-v1",provider_id="provider-v1",deployment_environment="CONTROLLED_PRODUCTION",checkpoint_id="checkpoint-v1",phase_id="phase-12",repository_head="commit-v1",full_regression_test_count=100,evaluated_at=_NOW,live_enablement_commit="enablement-commit-v1"));d.update(x);return LiveProviderActivationEvidenceV1(**d)
def _frozen(x):assert is_dataclass(x) and type(x).__dataclass_params__.frozen and "__dict__" not in type(x).__slots__
def test_public_contract_is_immutable_and_zero_authority():
 assert tuple(f.name for f in fields(LiveProviderActivationPolicyV1))==_P and tuple(f.name for f in fields(LiveProviderActivationEvidenceV1))==_E and tuple(f.name for f in fields(LiveProviderActivationDecisionV1))==_D and tuple(f.name for f in fields(LiveProviderActivationAuditEvidenceV1))==_A and tuple(f.name for f in fields(LiveProviderActivationFailureV1))==_F
 decision=evaluate_live_provider_activation_readiness_v1(_p(),_e());audit=build_live_provider_activation_audit_evidence_v1(_p(),_e(),decision)
 for x in (_p(),_e(),decision,audit):_frozen(x)
 with pytest.raises(FrozenInstanceError):_p().network_connection_authorized=True # type: ignore[misc]
def test_missing_governance_fails_closed_without_any_activation():
 d=evaluate_live_provider_activation_readiness_v1(_p(),_e(owner_authorized=False,repository_clean=False,credential_source_configured=False,reconciliation_ready=False))
 assert {"OWNER_AUTHORIZATION_REQUIRED","REPOSITORY_NOT_CLEAN","CREDENTIAL_SOURCE_NOT_CONFIGURED","RECONCILIATION_NOT_READY"}.issubset(d.failure_codes) and tuple(d.failure_codes)==tuple(sorted(d.failure_codes)) and set(d.failure_codes).issubset(_C) and not d.ready
 assert (d.credential_loading_authorized,d.network_connection_authorized,d.provider_transmission_authorized,d.production_runtime_authorized,d.publication_authorized,d.trading_authorized)==(False,)*6
def test_structural_readiness_is_only_eligible_for_separate_authorization():
 d=evaluate_live_provider_activation_readiness_v1(_p(),_e())
 assert d.ready and not any((d.credential_loading_authorized,d.network_connection_authorized,d.provider_transmission_authorized,d.production_runtime_authorized,d.publication_authorized,d.trading_authorized))
def test_audit_is_deterministic_identity_bound_and_non_operational():
 p,e=_p(),_e();d=evaluate_live_provider_activation_readiness_v1(p,e);assert build_live_provider_activation_audit_evidence_v1(p,e,d)==build_live_provider_activation_audit_evidence_v1(p,e,d)
 with pytest.raises(ValueError):build_live_provider_activation_audit_evidence_v1(p,_e(provider_id="other-provider-v1"),d)
